use crate::report_v2::{ToolResult, sha256_file};
use std::fs;
use std::path::Path;
use std::process::Command;

const SOURCE: &str = "shaders/native_gpu_rect.wesl";
const GENERATED_WGSL: &str = "crates/boon_native_gpu/src/generated/native_gpu_rect.wgsl";
const GENERATED_RUST: &str = "crates/boon_native_gpu/src/generated/shader_bindings.rs";

pub fn run(workspace: &Path, check: bool) -> ToolResult<()> {
    if check {
        verify_fresh(workspace)
    } else {
        generate(workspace)?;
        verify_fresh(workspace)
    }
}

fn generate(workspace: &Path) -> ToolResult<()> {
    let source = workspace.join(SOURCE);
    let generated_wgsl = workspace.join(GENERATED_WGSL);
    let generated_rust = workspace.join(GENERATED_RUST);
    let generated_dir = generated_rust
        .parent()
        .expect("generated Rust path has a parent");
    fs::create_dir_all(generated_dir)?;
    fs::copy(&source, &generated_wgsl)?;
    if generated_rust.exists() {
        fs::remove_file(&generated_rust)?;
    }

    let mut builder = wgsl_bindgen::WgslBindgenOptionBuilder::default();
    builder
        .workspace_root(generated_dir)
        .add_entry_point(generated_wgsl.display().to_string())
        .serialization_strategy(wgsl_bindgen::WgslTypeSerializeStrategy::Encase)
        .skip_hash_check(true)
        .output(&generated_rust)
        .build()?
        .generate()?;
    prepend_metadata(&generated_rust, sha256_file(&source)?.as_str())?;
    let status = Command::new("rustfmt").arg(&generated_rust).status()?;
    if !status.success() {
        return Err(format!("rustfmt failed for {}", generated_rust.display()).into());
    }
    println!("wrote {}", generated_rust.display());
    Ok(())
}

fn verify_fresh(workspace: &Path) -> ToolResult<()> {
    let source = workspace.join(SOURCE);
    let generated_wgsl = workspace.join(GENERATED_WGSL);
    let generated_rust = workspace.join(GENERATED_RUST);
    if fs::read(&source)? != fs::read(&generated_wgsl)? {
        return Err("generated native GPU WGSL is stale; run cargo xtask shaders".into());
    }
    let digest = sha256_file(&source)?;
    let bindings = fs::read_to_string(&generated_rust)?;
    for marker in [
        "SHADER_BINDING_GENERATOR: &str = \"wgsl_bindgen\"",
        "create_shader_module_embed_source",
        digest.as_str(),
    ] {
        if !bindings.contains(marker) {
            return Err(format!(
                "{} is stale or is not generated by wgsl_bindgen",
                generated_rust.display()
            )
            .into());
        }
    }
    println!("shader outputs are current");
    Ok(())
}

fn prepend_metadata(path: &Path, source_digest: &str) -> ToolResult<()> {
    let generated = fs::read_to_string(path)?;
    let metadata = format!(
        "// Generated by cargo xtask shaders.\n\
         // Source pipeline: shaders/*.wesl -> generated WGSL -> wgsl_bindgen Rust API.\n\n\
         pub const WGSL_BINDGEN_GENERATED: bool = true;\n\
         pub const SHADER_SOURCE_KIND: &str = \"wesl\";\n\
         pub const SHADER_BINDING_GENERATOR: &str = \"wgsl_bindgen\";\n\
         pub const NATIVE_GPU_RECT_WESL_SHA256: &str = \"{source_digest}\";\n\
         pub const NATIVE_GPU_SHADER_WESL_SHA256S: &[(&str, &str)] = &[\n\
             (\"{SOURCE}\", \"{source_digest}\"),\n\
         ];\n\n"
    );
    let mut output = String::new();
    let mut inserted = false;
    for line in generated.lines() {
        output.push_str(line);
        output.push('\n');
        if !inserted && line.trim_start().starts_with("#![allow(") {
            output.push_str(&metadata);
            inserted = true;
        }
    }
    if !inserted {
        output = format!("{metadata}{generated}");
    }
    fs::write(path, output)?;
    Ok(())
}
